11/23 issues
TEALSK12/introduction-to-computer-science pull request #370
Opened 2021-11-23 16:00 UTC by aspiece

2021-11-24 16:51 UTC, aspiece commented
Added Rachel and Dan. As soon as I someone can review this, it can get merged. I will be closing a bunch of issues, so more will be coming.

2021-11-29 19:01 UTC, Dan-TEALS requested changes
A few comments that should be corrected before merging. PowerPoint slides not reviewed.

2021-11-29 19:01 UTC, Dan-TEALS commented on docs/lab_42.md.html
> +| 3.1 sentence script  | 0.5 |
Inconsistent capitalization.

2021-11-29 20:43 UTC, aspiece commented
@Dan-TEALS  sorry, needed to add that and was still in this branch. Just added the resources from meetup #2.

2021-11-29 21:38 UTC, merged