Remove notes from slide 4
TEALSK12/introduction-to-computer-science pull request #371
Opened 2021-11-24 17:40 UTC by aspiece

2021-11-29 18:39 UTC, Dan-TEALS requested changes
Some changes that should be made to the updated files before committing. I wasn't really able to review the slide deck changes.

2021-11-29 18:39 UTC, Dan-TEALS commented on docs/lab_51.md.html
> +1. Each of the six students in your group should follow these instructions.  Each student should then follow his or her instructions, completing each corresponding step together.  (For example, every
"his or her" is not inclusive. Better to use "their."

2021-11-29 18:39 UTC, Dan-TEALS commented on docs/lab_51.md.html
> +2. What was the result of the group following the instructions?
What happened to 1?

2021-11-29 18:39 UTC, Dan-TEALS commented on docs/lab_51.md.html
> +| Part 3 refelction questions answered  | 0.5 |
_reflection_ misspelled.

2021-11-29 18:39 UTC, Dan-TEALS commented on lab_51.md
> +1. Each of the six students in your group should follow these instructions.  Each student should then follow his or her instructions, completing each corresponding step together.  (For example, every
"his or her" is not inclusive. Use "their."

2021-11-29 18:39 UTC, Dan-TEALS commented on lab_51.md
> +1. Each of the six students in your group should follow these instructions.  Each student should then follow his or her instructions, completing each corresponding step together.  (For example, every
Missing the close paren.

2021-11-29 18:39 UTC, Dan-TEALS commented on lab_51.md
> +2. What was the result of the group following the instructions?
What happened to 1?

2021-11-29 18:39 UTC, Dan-TEALS commented on lab_51.md
>  Assign each member of your group a different number from 1 to 6.  Each of the six students in your group should then follow these instructions.  Each student should then follow his or her instruction
Not one of the changes you made, but the instructions in this paragraph are also not inclusive. (Change "his or her" to "their.") Also, you changed the Roman numerals to a section number elsewhere. Should that have been done here?

2021-11-29 18:39 UTC, Dan-TEALS commented on lab_51.md
> +| Part 3 refelction questions answered  | 0.5 |
_reflection_ misspelled.

2021-12-08 13:49 UTC, aspiece commented on docs/lab_51.md.html
> +2. What was the result of the group following the instructions?
Good question. LOL

2021-12-08 13:58 UTC, aspiece commented
I am not sure where I used roman numerals. I try to stick to bullets and numbers. Andrew

2021-12-13 18:25 UTC, Dan-TEALS commented
> 

On line 100 of the change file, there's a statement that "everybody should complete their step ii, at the same time." Elsewhere that was changed to "step 2."

2022-01-05 18:49 UTC, merged

2022-01-05 18:53 UTC, aspiece commented
@nikmolnar  Thank you for the reminder. I needed to resolve the conflicts. The html version and ppt should be up to date now. I will update the lab documents in the next PR.